name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        workspace: [src, examples/*]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: Install Dependencies
        run: yarn install --frozen-lockfile

      - name: Lint
        run: yarn workspace ${{ matrix.workspace }} lint

      - name: Test
        run: yarn workspace ${{ matrix.workspace }} test

      - name: Build
        run: yarn workspace ${{ matrix.workspace }} build
